sudo: required
dist: trusty
language: node_js
node_js: "6"
services:
  - postgresql
addons:
  - postgresql: "9.6"
env:
 - TEST_DBURL=postgres://postgres@localhost:5432/doc-man-test
branches:
  only:
    - development
before_script:
  - psql -c 'create database doc-man-test;' -U postgres

script:
  - npm test
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_success:
 - npm run coverage